export const ActionTypes = {
    SELECTED_VALIDATION_QUESTION:"SELECTED_VALIDATION_QUESTION",
    BACK_NAVIGATIONS:"BACK_NAVIGATIONS",
    SELECTED_GENDER:"SELECTED_GENDER",
    SPINNER_FLAG:'SPINNER_FLAG'

}